[package]
name = "quantum_consciousness"
version = "0.1.0"
edition = "2021"

[lib]
name = "quantum_consciousness"
crate-type = ["cdylib"]

[dependencies]
rand = "0.8"
pyo3 = { version = "0.20", features = ["extension-module"] }